//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFB.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int ID_Category { get; set; }
        public int ID_User { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
